### ISSUE TITLE
Error in modbase-walkthrough

### ISSUE THREAD

**Issue by fneuh** [nanoporetech/taiyaki#11]
Hi,
I am trying to run taiyaki on the data provided in the walkthrough for modified base detection. I installed taiyaki in a virtual environment (taiyaki 4.1.0, torch 1.1.0, numpy 1.16.3).

When running prepare_mapped_reads.py, like this on a GPU, I get the following error message:

prepare_mapped_reads.py --limit 100 --mod Z C 5mC --mod Y A 6mA reads flo_files/read_params.tsv flo_files/mapped_reads.hdf5 pretrained/r941_dna_minion.checkpoint modbase_references.fasta --overwrite

Running prepare_mapping using flip-flop remapping
Converting references to labels using canonical alphabet ACGT with modified base(s) Y=6mA (alt to A), Z=5mC (alt to C)
~/miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/serialization.py:454: SourceChangeWarning: source code of class 'taiyaki.layers.Serial' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
.... more _SourceChangeWarnings_
~/miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
* 82 reads failed to produce remapping results due to: Failure applying basecall network to remap read.
* 18 reads failed to produce remapping results due to: No fasta reference found.

I narrowed the problem down to line 65 in prepare_mapping_funcs.py:
transweights = modelOnDevice(signalTensor).cpu().numpy()

File "/users/bsg/kjv309/miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/prepare_mapping_funcs.py", line 65, in oneread_remap
    transweights = modelOnDevice(signalTensor).cpu().numpy()

When removing the try .. except statement for this line I get the following error text:

Traceback (most recent call last):
  File "./miniconda3/envs/flo_taiyaki/bin/prepare_mapped_reads.py", line 4, in <module>
    \__import__('pkg_resources').run_script('taiyaki==4.1.0', 'prepare_mapped_reads.py')
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/pkg_resources/\__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/pkg_resources/\__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/gpfs0/./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/prepare_mapped_reads.py", line 83, in <module>
    main()
  File "/gpfs0/./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/prepare_mapped_reads.py", line 79, in main
    results, args.output, alphabet_info)
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/prepare_mapping_funcs.py", line 102, in generate_output_from_results
    for resultdict, mesg in results:
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/iterators.py", line 353, in imap_mp
    for r in map(my_function, args):
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/prepare_mapping_funcs.py", line 65, in oneread_remap
    transweights = modelOnDevice(signalTensor).cpu().numpy()
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 493, in \__call__
    result = self.forward(*input, **kwargs)
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/layers.py", line 487, in forward
    x = layer(x)
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 493, in \__call__
    result = self.forward(*input, **kwargs)
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/layers.py", line 426, in forward
    out = self.activation(self.conv(self.pad(x)))
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 493, in \__call__
    result = self.forward(*input, **kwargs)
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/nn/modules/conv.py", line 190, in forward
    if self.padding_mode == 'circular':
  File "./miniconda3/envs/flo_taiyaki/lib/python3.6/site-packages/torch-1.1.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 539, in \__getattr__
    type(self).\__name__, name))
AttributeError: 'Conv1d' object has no attribute 'padding_mode'

Is this an issue concerning torch (related to the warnings) or something else? Do you have ideas on this issue?

Thanks,
Florian

**Comment by myrtlecat** [comment]
This appears to be due to a changes introduced in pytorch 1.1 being incompatible with the models that we provide (which were created using pytorch 1.0).

If possible, please try downgrading to pytorch 1.0 while we work on a fix.

**Comment by tmassingham-ont** [comment]
Hello.  How did you install Taiyaki please?  Our install script `make install, which creates a virtual environment for Taiyaki, which installs the correct version of Pytorch.

**Comment by fneuh** [comment]
I installed it with 'python3.6 setup.py install' , so that I could use it in a conda environment. I tried out installing it via 'make install', getting the correct pytorch version, it works now.

Thanks for the help!
