### ISSUE TITLE
Distributed multiple GPUs launch failed

### ISSUE THREAD

**Issue by weir12** [nanoporetech/taiyaki#112]
Hi:
The following error occurred when I used the script to test the multi-GPU training capability.
I have  2080ti*4 graphics cards on the same machine
workflow/test_multiGPU.sh
```
+ set -o pipefail
+ TAIYAKI=.
+ echo ''

+ echo 'Test of multi-GPU training with train_flipflop.py'
Test of multi-GPU training with train_flipflop.py
+ echo ''

+ OPENBLAS_NUM_THREADS=1
+ export OPENBLAS_NUM_THREADS
+ OMP_NUM_THREADS=4
+ export OMP_NUM_THREADS
+ NGPU=2
+ MAPPEDREADFILE=./test/data/mapped_signal_file/mapped_reads_1.hdf5
+ MODEL=./models/mGru_flipflop.py
+ RESULT_DIR=./workflow/multiGPU_test_results
+ LR_MAX=0.003
+ LR_MIN=0.00015
+ ITERATIONS=100
+ WARMUP=10
+ python -m torch.distributed.launch --nproc_per_node 2 --master_addr 127.0.0.2 --master_port 29501 ./bin/train_flipflop.py --overwrite --min_sub_batch_size 32 --warmup_batches 10 --niteration 100 --lr_max 0.003 --lr_min 0.00015 --outdir ./workflow/multiGPU_test_results ./models/mGru_flipflop.py ./test/data/mapped_signal_file/mapped_reads_1.hdf5
Traceback (most recent call last):
  File "./bin/train_flipflop.py", line 703, in <module>
    main(get_train_flipflop_parser().parse_args())
  File "./bin/train_flipflop.py", line 688, in main
    res_info, logs = parse_init_args(args)
  File "./bin/train_flipflop.py", line 253, in parse_init_args
    logs = LOGS(main=helpers.Logger(main_log_fn, args.quiet))
  File "/home/weir/m6a_model/software/taiyaki-master/taiyaki/helpers.py", line 280, in __init__
* Using random seed: 2218333279
    self.fh = open(log_file_name, 'wb', 0)
FileNotFoundError: [Errno 2] No such file or directory: './workflow/multiGPU_test_results/model.log'
Killing subprocess 72870
Killing subprocess 72871
Traceback (most recent call last):
  File "/home/weir/anaconda3/envs/dp/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/weir/anaconda3/envs/dp/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/weir/anaconda3/envs/dp/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/weir/anaconda3/envs/dp/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/weir/anaconda3/envs/dp/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/weir/anaconda3/envs/dp/bin/python', '-u', './bin/train_flipflop.py', '--local_rank=1', '--overwrite', '--min_sub_batch_size', '32', '--warmup_batches', '10', '--niteration', '100', '--lr_max', '0.003', '--lr_min', '0.00015', '--outdir', './workflow/multiGPU_test_results', './models/mGru_flipflop.py', './test/data/mapped_signal_file/mapped_reads_1.hdf5']' returned non-zero exit status 1.
```

**Comment by weir12** [comment]
CUDA_VISIBLE_DEVICES should be set before training to show which graphics cards are available for the program
