### ISSUE TITLE
prepare_mapped_reads.py on RNA fails with TypeError: '<' not supported between instances of 'numpy.str_' and 'int' 

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/taiyaki#18]
Hi, I get an error when running `prepare_mapped_reads.py` on direct RNA reads with m6A. [I've run it previously with DNA without any problem](https://github.com/nanoporetech/taiyaki/blob/master/docs/modbase.rst), so that's odd to me. 

```
prepare_mapped_reads.py --jobs 6 --mod = A 6mA reads read_params.tsv mapped_reads.hdf5 pretrained/r941_rna_minion.checkpoint read_references.fasta

"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/lpryszcz/src/taiyaki/taiyaki/prepare_mapping_funcs.py", line 50, in oneread_remap
    sig.set_trim_absolute(read_params_dict['trim_start'], read_params_dict['trim_end'])
  File "/home/lpryszcz/src/taiyaki/taiyaki/signal.py", line 66, in set_trim_absolute
    if trimstart < 0 or trimend < 0:
TypeError: '<' not supported between instances of 'numpy.str_' and 'int'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lpryszcz/src/taiyaki/venv/bin/prepare_mapped_reads.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lpryszcz/src/taiyaki/bin/prepare_mapped_reads.py", line 83, in <module>
    main()
  File "/home/lpryszcz/src/taiyaki/bin/prepare_mapped_reads.py", line 79, in main
    results, args.output, alphabet_info)
  File "/home/lpryszcz/src/taiyaki/taiyaki/prepare_mapping_funcs.py", line 101, in generate_output_from_results
    for resultdict, mesg in results:
  File "/home/lpryszcz/src/taiyaki/taiyaki/iterators.py", line 361, in imap_mp
    for r in mapper(my_function, args, chunksize=chunksize):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 369, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 761, in next
    raise value
TypeError: '<' not supported between instances of 'numpy.str_' and 'int'
Exception ignored in: <generator object iterate_files_reads_unpaired at 0x7f6eef0176d0>
Traceback (most recent call last):
  File "/home/lpryszcz/src/taiyaki/taiyaki/fast5utils.py", line 63, in iterate_files_reads_unpaired
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.6/site-packages/ont_fast5_api/fast5_file.py", line 52, in __exit__
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.6/site-packages/ont_fast5_api/fast5_file.py", line 78, in close
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 289, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-tnf92dft-build/h5py/_objects.c:2853)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-tnf92dft-build/h5py/_objects.c:2811)
  File "h5py/h5f.pyx", line 234, in h5py.h5f.get_obj_ids (/tmp/pip-tnf92dft-build/h5py/h5f.c:3450)
  File "h5py/h5i.pyx", line 37, in h5py.h5i.wrap_identifier (/tmp/pip-tnf92dft-build/h5py/h5i.c:1145)
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by lpryszcz** [comment]
Ok, I know what's the problem. I've concatenated `read_params.tsv` from several libraries that I've processed separately. And becuase of that the file header was appearing in the middle of the file as well. And this cause the `prepare_mapped_reads.py` to crash... 
The way to go is:
```echo -e 'UUID\ttrim_start\ttrim_end\tshift\tscale' > read_params.tsv; 
tail -qn +2 *.read_params.tsv >> read_params.tsv```

Note, you should catch improper lines in `read_params.tsv`.
