### ISSUE TITLE
basecall.py fails with RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by lpryszcz** [nanoporetech/taiyaki#24]
Hi, `basecall.py` fails with `CUDA out of memory` toward the end of basecalling - that's odd as processing first 1-4k reads used ~5GB of vRAM on GTX 1080 Ti (11 GB vRAM), thus I don't see any reason why this should happen. In contrast guppy 3.1.5 runs just fine with the same model...

```
Traceback (most recent call last):
  File "/home/lpryszcz/src/taiyaki/venv/bin/basecall.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 198, in <module>
    main()
  File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 177, in main
    is_cat_mod, mods_fp)
  File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 83, in process_read
    out = model(torch.tensor(chunks, device=device))
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 487, in forward
    x = layer(x)
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 80, in forward
    return reverse(self.layer(reverse(x)))
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 362, in forward
    y, hy = self.cudnn_gru.forward(x)
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 7.02 GiB (GPU 0; 10.92 GiB total capacity; 3.63 GiB already allocated; 6.07 GiB free; 647.31 MiB cached)
```

**Comment by lpryszcz** [comment]
it still fails, it looks that the vRAM memory is not released after basecalling batches of reads... 
Usually it fails after a few thousands reads, but sometimes it happens after a few hundred! Any idea? 
```
..................................................    8850
................................Traceback (most recent call last):
File "/home/lpryszcz/src/taiyaki/venv/bin/basecall.py", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 198, in <module>
main()
File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 177, in main
is_cat_mod, mods_fp)
File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 83, in process_read
out = model(torch.tensor(chunks, device=device))
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 487, in forward
x = layer(x)
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 80, in forward
return reverse(self.layer(reverse(x)))
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 362, in forward
y, hy = self.cudnn_gru.forward(x)
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in forward
self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 7.61 GiB (GPU 0; 10.92 GiB total capacity; 3.94 GiB already allocated; 1.85 GiB free; 4.55 GiB cached)
```

```
* Calling reads.
..................................................      50
..................................................     100
..........................Traceback (most recent call last):
File "/home/lpryszcz/src/taiyaki/venv/bin/basecall.py", line 7, in <module>
exec(compile(f.read(), __file__, 'exec'))
File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 198, in <module>
main()
File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 177, in main
is_cat_mod, mods_fp)
File "/home/lpryszcz/src/taiyaki/bin/basecall.py", line 83, in process_read
out = model(torch.tensor(chunks, device=device))
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 487, in forward
x = layer(x)
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 80, in forward
return reverse(self.layer(reverse(x)))
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 362, in forward
y, hy = self.cudnn_gru.forward(x)
File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in forward
self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 7.38 GiB (GPU 0; 10.92 GiB total capacity; 3.82 GiB already allocated; 6.19 GiB free; 333.31 MiB cached)
```

**Comment by myrtlecat** [comment]
My apologies, the memory management in `basecall.py` is not great. I'll try to explain below what the problems are, and we are aiming to improve this situation.

In the interim, the best advice is to try to basecall reads in small batches, and accept that some jobs may have to be retried. Some reads (probably longer ones) might not basecall at all until we make some improvements (see below). If using guppy is an option that should usually be preferred. `basecall.py` enables us to quickly test new networks that aren't yet supported by guppy, but guppy will always be more robust and performant.

There are two things wrong with memory management in `basecall.py`:
1. `basecall.py` is written entirely using pytorch. The memory management in pytorch happens via python's garbage collector, which means that the exact time that memory gets freed is non-deterministic. This is why basecalling the same reads can fail at different times. In contrast, guppy is written in C++/CUDA and should have much more robust and reliable memory management; the freeing of GPU memory can be precisely controlled and is deterministic.
2. We basecall entire reads all at once. This means that any particularly long reads can cause out of memory errors on the GPU. What we should be doing is breaking up long reads into pieces and then stitching the calls beck together. This improvement is planned, and it should land in the next release. Hopefully it will make things much more robust.

**Comment by lpryszcz** [comment]
Cool, thanks for the details! 

>  If using guppy is an option that should usually be preferred.  

That'd would be an option if only guppy reported modified bases as well ;) Or am I missing something? Is it possible to play with guppy3 config in such way that it reports alternative bases call above certain threshold? 

> The memory management in pytorch happens via python's garbage collector, which means that the exact time that memory gets freed is non-deterministic. 

Naive question, wouldn't `import gc; gc.collect()` do the job?

**Comment by myrtlecat** [comment]
> That'd would be an option if only guppy reported modified bases as well ;) Or am I missing something?

You're not missing anything, support for mod-bases in guppy is planned and coming soon (see 23 minutes into [this talk](https://nanoporetech.com/about-us/news/london-calling-clive-brown-and-team-plenary) for the announcement).

> Naive question, wouldn't import gc; gc.collect() do the job?

I hope it is that simple! We'll give it a try.

**Comment by lpryszcz** [comment]
Also, you may want to have a look at https://discuss.pytorch.org/t/i-run-out-of-memory-after-a-certain-amount-of-batches-when-training-a-resnet18/1911/10

or `torch.cuda.empty_cache()`
