### ISSUE TITLE
train network with mapped_reads.hdf5 supplied in the intermediate_files

### ISSUE THREAD

**Issue by wxuzhang** [nanoporetech/taiyaki#36]
Hi,
When I go through the process in the walkthrough process, I am trying to train the neural network with the data mapped_reads.hdf5 supplied in the intermediate_files. Then I received the following error:

(taiyaki) wenxu@wenxu-C9X299-PG300F:~/Documents/nanopore/demo$ train_flipflop.py --device 0 /home/wenxu/Downloads/taiyaki-master/models/mGru_flipflop.py training mapped_reads.hdf5
* Taiyaki version 4.1.0
* Command line
/home/wenxu/Downloads/taiyaki-master/venv/bin/train_flipflop.py --device 0 /home/wenxu/Downloads/taiyaki-master/models/mGru_flipflop.py training mapped_reads.hdf5
* Loading data from mapped_reads.hdf5
* Per read file MD5 fc5b1e9f9399df2a89811755e070e73b
* Reads not filtered by id
Traceback (most recent call last):
  File "/home/wenxu/Downloads/taiyaki-master/venv/bin/train_flipflop.py", line 4, in <module>
    __import__('pkg_resources').run_script('taiyaki==4.1.0', 'train_flipflop.py')
  File "/home/wenxu/Downloads/taiyaki-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/wenxu/Downloads/taiyaki-master/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/home/wenxu/Downloads/taiyaki-master/venv/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/train_flipflop.py", line 277, in <module>
    main()
  File "/home/wenxu/Downloads/taiyaki-master/venv/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/EGG-INFO/scripts/train_flipflop.py", line 113, in main
    with mapped_signal_files.HDF5Reader(args.input) as per_read_file:
  File "/home/wenxu/Downloads/taiyaki-master/venv/lib/python3.6/site-packages/taiyaki-4.1.0-py3.6-linux-x86_64.egg/taiyaki/mapped_signal_files.py", line 526, in __init__
    assert self.version == _version, 'Incorrect file version, got {} expected {}'.format(self.version, _version)
AssertionError: Incorrect file version, got 7 expected 8

Is there any help on this? Thanks!

**Comment by myrtlecat** [comment]
Apologies for this, we have made some (minor) changes to the data format with the latest taiyaki release.

There is a [script](https://github.com/nanoporetech/taiyaki/blob/928aaaf5d3437292717847d03079fdb938d60524/misc/upgrade_mapped_signal.py) provided that can convert the old format to the new one:

```
# From taiyaki source directory
misc/upgrade_mapped_signal.py mapped_reads.hdf5
```

The upgrade happens in-place. I hope this helps.

**Comment by wxuzhang** [comment]
Thanks. It works.

**Comment by tmassingham-ont** [comment]
The source `mapped_reads.hdf5` file has now been updated.
