### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/taiyaki#9]
I am unsure whether to place here or on some CUDA specific thread. 

getting to final step of training data on IVT RNA synthesized with modified base. Most reads could not be resquiggled, I guess because of the higher error rate relating to modified base completely replacing U in the T7 pol mix. 

I am running out of room on the GPU but running nvidia-smi seems plenty of space free. 

`/taiyaki/venv/bin/train_flipflop.py --device 0 models/mGru_flipflop.py training mapped_reads.hdf5 --overwrite
* Loading data from mapped_reads.hdf5
* Per read file MD5 5f26a4f43d3e2acd15d8d65f6167136c
* Reads not filtered by id
* Loaded 148 reads.
* Sampled 1000 chunks: median(mean_dwell)=37.97, mad(mean_dwell)=12.13
* Reading network from models/mGru_flipflop.py
* Network has 1989160 parameters.
* Dumping initial model
* Training
....Traceback (most recent call last):
  File "/taiyaki/venv/bin/train_flipflop.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/taiyaki/bin/train_flipflop.py", line 251, in <module>
    main()
  File "/taiyaki/bin/train_flipflop.py", line 203, in main
    loss.backward()
  File "/taiyaki/venv/lib/python3.5/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/taiyaki/venv/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 125.38 MiB (GPU 0; 5.93 GiB total capacity; 5.21 GiB already allocated; 119.06 MiB free; 17.47 MiB cached)`

Anyone have experience with troubleshooting this. The GPU is NVIDIA GeForce GTX 1060.

**Comment by tmassingham-ont** [comment]
Hi.  Pytorch allocates memory on GPU dynamically, so `nvidia-smi` may not show the instantaneous amount in use.  The error message suggests that almost all of the memory has been allocated.

Two possible solutions, depending on your goals, are:
- add `--size 96` to train a smaller model (size=96 is a fast model, size=256 is high accuracy)
- add `--min_batch_size 48` to reduce the batch size (default is set for GPUs with 8G)

Good luck training.

**Comment by lpryszcz** [comment]
Hi I have similar issue. It's weird, as I only 4.36 GB out of 10.92 is allocated, still `train_abinitio.py` claims only 1.22 GiB is free. Could it be a bug? 

```
time train_abinitio.py --device cuda:0 $HOME/src/taiyaki/models/mGru_flipflop.py chunks.hdf5 chunks.fa
* Taiyaki version 4.1.0
* Command line
/home/lpryszcz/src/taiyaki/venv/bin/train_abinitio.py --device cuda:0 /home/lpryszcz/src/taiyaki/models/mGru_flipflop.py chunks.hdf5 chunks.fa
* Loading data from chunks.hdf5
* Per read file MD5 ce162d56e27817a1f8c60e02e7a0ea28
* Loaded 44735 reads from chunks.hdf5.
* Loaded references from chunks.fa.
* Written pickle of processed references to chunks.pkl for future use.
* Reading network from /home/lpryszcz/src/taiyaki/models/mGru_flipflop.py
* Network has 285160 parameters.
* Dumping initial model
* Training
Traceback (most recent call last):
  File "/home/lpryszcz/src/taiyaki/venv/bin/train_abinitio.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/lpryszcz/src/taiyaki/bin/train_abinitio.py", line 168, in <module>
    outputs = network(indata)
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 487, in forward
    x = layer(x)
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 80, in forward
    return reverse(self.layer(reverse(x)))
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lpryszcz/src/taiyaki/taiyaki/layers.py", line 362, in forward
    y, hy = self.cudnn_gru.forward(x)
  File "/home/lpryszcz/src/taiyaki/venv/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 1.37 GiB (GPU 0; 10.92 GiB total capacity; 4.36 GiB already allocated; 1.23 GiB free; 386.00 KiB cached)
```

**Comment by tmassingham-ont** [comment]
Yes, this looks suspicious.  There is a large gap between the sum of the amount allocated and amount free, and the total capacity: is there any chance that another process is running on the GPU at the same time?
To help replicate, which version of pytorch & CUDA are you using please?

**Comment by lpryszcz** [comment]
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
on GTX1080 Ti
